version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run: apt update
      - run: DEBIAN_FRONTEND=noninteractive TZ=Europe/Brussels apt install -y gcc g++ libsfml-dev cmake git
      - run: mkdir -p build
      - run: cd build && cmake ..
      - run: cd build && make
      - run: cd build && make install

  run_tests:
    resource_class: large
    docker:
      - image: ubuntu:22.04
    steps:
      - run: mkdir output
      - run: ls -a
      - run: pwd
      - run: cd working && ./../build/testing/testing/TESTS

workflows:
  default_validation:
    jobs:
      - build
      - run_tests:
          requires:
            - build
