version: 2.1


executors:
  main_executor:
    docker:
      - image: ubuntu:22.04


jobs:
  build:
    resource_class: small
    executor: main_executor
    steps:
      - checkout
      - run: apt update
      - run: DEBIAN_FRONTEND=noninteractive TZ=Europe/Brussels apt install -y gcc g++ libsfml-dev cmake git
      - run: mkdir -p build
      - run: cd build && cmake ..
      - run: cd build && make
      - run: cd build && make install
      - persist_to_workspace:
          paths:
            - testing/testing/TESTS
          root: build

  run_tests:
    resource_class: large
    executor: main_executor
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: cd working && mkdir -p output
      - run: cd working && ./../build/testing/testing/TESTS

workflows:
  default_validation: &default_validation
    jobs:
      - build
      - run_tests:
          requires:
            - build